### ISSUE TITLE
Add RETENTION power level

### ISSUE THREAD

**Issue by BlackSoulxxx** [libxzr/KonaBess#10]
Hello, I would like to suggest the dev to add into the app with RETENTION power level for supported devices.
For example with Xiaomi kona (sm8250)
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/alioth-r-oss/include/dt-bindings/regulator/qcom%2Crpmh-regulator-levels.h
and Xiaomi lahaina (sm8350)
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/haydn-r-oss/include/dt-bindings/regulator/qcom%2Crpmh-regulator-levels.h

**Comment by CHECK-1234** [comment]
I testest this retention power level on sdm845 on setting the gpu frequency on 80mhz, and it works!

I manually editted vdd-level-sdm845.h and added "VDD_GX_RETENTION" in "enum vdd_gx_levels {"

And went into gpucc-sdm845.c and added "RPMH_REGULATOR_LEVEL_RETENTION" in "static int vdd_gx_corner[] = {" 

Then in gpucc-sdm845.c, replaced "VDD_GX_MIN" with "VDD_GX_RETENTION" in "static void gpu_cc_gfx_sdm845_fixup_sdm845v2(void)"

And compiled the kernel and installed it and went into /sys/kernel/debug/opp/soc-5000000.qcom,kgsl-3d0/opp:80000000/u_volt_target and then I noticed that instead of it saying "49", now it says "17".

Now i can run 80mhz at around maybe 1/3 the voltage

This should be added to konabess

**Comment by libxzr** [comment]
I'm curious how much difference there is between RETENTION and MIN_SVS. Someone tested it before and find no difference in power cost compared to MIN_SVS. If so, I won't add this level to confuse people. Btw, three times the value of the level does not mean that the voltage is also three times.

**Comment by libxzr** [comment]
https://github.com/libxzr/KonaBess/commit/90d5e7321658641db8ee3932ec39f6a7866d9f51

**Comment by ElDavoo** [comment]
Is retention really the lowest possible voltage? Looks like I'm running 525mhz on retention (setting all voltages in the gpu voltage table in konabess) and clearly it should not be possible.
Fyi, using a 10t pro with 865 (sm8250); [this ](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/apollo-q-oss/include/dt-bindings/regulator/qcom%2Crpmh-regulator-levels.h) should be the table
